---
title: "GenoBrew_CNV_profile_res"
output: html_document
---
# CNV Profile Results

## Interactive CNV Profile Plot

After loading the input files, users can visualize the CNV profiles by selecting samples or 
families through two different tabs. The **CNV Profile** plot is the result from Qploidy2 
`compare_cn_track()` function and is interactive and powered by Plotly. Access more details
about the plot by 

### Plot Layout

- **Rows**: Represent individual samples
- **Columns**: Represent chromosomes
- **Cells**: Filled with colors indicating copy number variations (CNVs):
  - **Gray**: User-defined ploidy
  - **Blue**: Loss of copy number relative to the ploidy
  - **Red**: Gain of copy number relative to the ploidy

### Interactive Features

Hovering over a cell provides detailed information, including:

- **Sample**: Identifier for the sample
- **Chromosome**: Chromosome name
- **Start**: Start position of the CN window in the genome
- **End**: End position of the CN window in the genome
- **CN Value**: Maximum posterior copy number value estimated by the HMM
- **BAF Weight**: B-allele frequency weight used by the model

## BAF and Z-Scores Box

Users can interact with the **CNV Profile** plot by clicking on a specific cell to update 
the sample visualized in the **BAF and Z-Scores** box. The selected sample corresponds to the 
row of the clicked point.

### Plot Details

The **BAF and Z-Scores** box displays results generated by the 
Qploidy2 package's `plot_cn_track()` function. It includes the following visualizations:

1. **BAF Density Plot** (Top Left):
   - Displays the density of B-allele frequencies (BAF) for all markers in the selected sample

2. **BAF Distribution Across the Genome** (Below Density Plot):
   - **Y-Axis**: BAF values
   - **X-Axis**: Genomic positions
   - Chromosomes are split into separate columns

3. **Z-Scores Distribution Across the Genome** (Below BAF):
   - **Y-Axis**: Z-scores
   - **X-Axis**: Genomic positions
   - Chromosomes are split into separate columns

4. **Estimated CN by Chromosome Position** (Below Z-Scores):
   - Displays the estimated copy number (CN) across chromosome positions

### Export Options

#### Image Export

Users can save the plot in various formats, including HTML, JPEG, TIFF, SVG, and PNG, by 
clicking the **Save** button.

#### Updated HMM files

The HMM results files (by marker, by window and parameters) are updated in case you re-run the HMM 
for some samples and clicked in the "Update full results" button. These updated files can be 
downloaded by clicking the **Download HMM files** button.