---
title: "GenoBrew_CNV_profile_par"
output: html_document
---

# Supported Input Types for GenoBrew CNV Profile

## HMM Results by Marker

HMM-based copy number (CN) estimates for each marker (variant site) in the 100k marker panel. 
Columns include:

- **Chr**: Chromosome name
- **__w__**: Weight for the marker
- **MarkerName**: Name of the marker
- **SampleName**: Identifier for the sample
- **X**: X-coordinate for the marker
- **Y**: Y-coordinate for the marker
- **R**: Intensity value for the marker
- **ratio**: Ratio value for the marker
- **geno**: Genotype call for the marker
- **baf**: B-allele frequency for the marker
- **z**: Z-score for the marker
- **Position**: Genomic position of the marker
- **outlier**: Outlier status for the marker
- **w_baf**: Weighted B-allele frequency for the marker
- **CN_call**: Copy number call for the marker
- **post_max**: Maximum posterior probability for the copy number call


## Qploidy2 HMM Results by Window

One of the files produced by Qploidy2 function `write_hmm_CN()`. It is the result from HMM-based copy 
number estimates summarized in genomic windows (e.g., 100kb or 1Mb bins). 
Columns include:

- **Sample**: Identifier for the sample
- **Chr**: Chromosome name
- **WindowID**: Unique identifier for the genomic window
- **Start**: Start position of the window in base pairs
- **End**: End position of the window in base pairs
- **n_snps**: Number of SNPs within the window
- **n_het**: Number of heterozygous SNPs within the window
- **z**: Z-score for the window
- **w_baf**: B-allele frequency HMM weight for the window
- **CN_call**: Copy number call for the window
- **post_max**: Maximum posterior probability for the copy number call
- **post_CN1**: Posterior probability for copy number 1
- **post_CN2**: Posterior probability for copy number 2
- **post_CN3**: Posterior probability for copy number 3
- **post_CN4**: Posterior probability for copy number 4
- **post_CN5**: Posterior probability for copy number 5
- **post_CN6**: Posterior probability for copy number 6


## HMM Parameters

RDS (R serialized) file containing the parameters and model objects used for HMM CN estimation. 
It is composed of a list with each item by sample. The following HMM parameters are described:

- **cn_grid**: Copy number grid
- **distribution**: Distribution model used
- **mu**: Mean values for the HMM states
- **sigma**: Standard deviation for the HMM states
- **A**: Transition probability matrix
- **pi0**: Initial state probabilities
- **bins**: Genomic bins used for the analysis
- **bw**: Bandwidth parameter
- **loglik**: Log-likelihood of the model
- **z_range**: Range of Z-scores
- **het_quantile**: Quantile for heterozygous SNPs
- **baf_weight**: Weight for B-allele frequency
- **transition_jump**: Transition jump parameter
- **z_only**: Z-score only flag
- **exp_ploidy**: Expected ploidy
- **rm_outliers**: Remove outliers flag
- **outlier_alpha**: Alpha parameter for outlier detection
- **segment_zscore**: Z-score for segmentation
- **snps_per_window**: Number of SNPs per window
- **min_snps_per_window**: Minimum number of SNPs per window
- **add_uniform**: Add uniform distribution flag
- **uniform_weight**: Weight for the uniform distribution


## Passport File

Contains pedigree information for each sample. Columns include:

- **ID**: Sample identifier
- **generation**: Generation or cohort information
- **Female.Parent**: Identifier for the female parent
- **Male.Parent**: Identifier for the male parent
- **fam**: Family or group identifier

Example:

```tsv
ID	generation	Female.Parent	Male.Parent	fam
Sample1	Parent				1
Sample2	Parent				1,2
Sample3	Parent				2
Sample4	F1  Sample1	Sample2		1
Sample5	F1  Sample2 Sample3			2
Sample6	F2  Sample4 Sample5			1,2
Sample7	F2  Sample4 Sample5			1,2
```

## Re-run HMM for specific sample changing parameters

Within the box "Adjust HMM parameters for this sample", users can re-run the HMM for a 
specific sample by changing the parameters and clicking the "Run analysis" button. Input required:

### Qploidy Standardized File

Standardized marker-level data (e.g., normalized read depth, B-allele frequency, etc.), 
used as input for CN estimation. Columns include:

- **MarkerName**: Name of the marker
- **SampleName**: Identifier for the sample
- **X**: Reference allele counts
- **Y**: Alternate allele counts
- **R**: Total counts for the marker
- **ratio**: Ratio (Alternative/(Alternative + Reference)) value for the marker

GenoBrew will run Qploidy2 `hmm_estimate_CN()` function using the standardized data and the specified 
parameters, and will update the CNV profile plot and BAF/Z-scores visualizations accordingly. For
detailed information about the parameters, please refer to the Qploidy2 documentation for `?hmm_estimate_CN`.

The feature can be used multiple times to edit different samples. The button "Update full results" will 
update the HMM results files (by marker, by window and parameters) with the new results from the 
re-run analysis. The button should be clicked after you have re-run the HMM for each sample you 
wanted to edit, and before downloading the updated files.