#' Example UI Function
#'
#' @description A shiny Module.
#'
#' @param id,input,output,session Internal parameters for {shiny}.
#'
#' @noRd
#'
#' @importFrom shiny NS tagList
#' @import shinydisconnect
#' @importFrom plotly plotlyOutput renderPlotly
mod_cnv_ui <- function(id){
  ns <- NS(id)
  tagList(
    fluidRow(
      disconnectMessage(
        text = "An unexpected error occurred, please reload the application and check the input file(s).",
        refresh = "Reload now",
        background = "white",
        colour = "grey",
        overlayColour = "grey",
        overlayOpacity = 0.3,
        refreshColour = "purple"
      ),
      column(width = 12,
             box(title = "Inputs", width = 12, collapsible = TRUE, collapsed = FALSE, status = "info", solidHeader = TRUE,
                 # --- Upload (left) | OR divider | Built-in (right) ---
                 div(style = "position:relative;",
                     # OR divider - absolutely centered, spans full height
                     div(style = paste(
                       "position:absolute; left:calc(41.66% + 4px); top:0; bottom:0;",
                       "display:flex; flex-direction:column; align-items:center;",
                       "width:50px; margin-left:-25px; z-index:1; user-select:none;"
                     ),
                     div(style = "flex:1; width:1px; background:#ccc;"),
                     div(style = paste(
                       "background:#6c757d; color:white; border-radius:50%;",
                       "width:32px; height:32px; display:flex; align-items:center;",
                       "justify-content:center; font-size:12px; font-weight:bold; flex-shrink:0;"
                     ), "OR"),
                     div(style = "flex:1; width:1px; background:#ccc;")
                     ),
                     # Qploidy info banner (spans full width above both sides)
                     fluidRow(
                       column(width = 5,
                              div(style = "background:#eef6fb; border-left:4px solid #17a2b8; border-radius:4px; padding:10px 14px; margin-bottom:10px; font-size:13px;",
                                  HTML(paste0(
                                    "<b>Files generated by Qploidy</b> &mdash; use ",
                                    "<code>write_hmm_CN()</code> to export three output files:<br>",
                                    "<code>*_by_marker.csv</code>, <code>*_by_window.csv</code>, ",
                                    "<code>*_params.rds</code>.<br>",
                                    "<span style='color:#6c757d;'>See ",
                                    "<a href='https://gabrielgesteira.github.io/Qploidy/' target='_blank'>Qploidy documentation</a>",
                                    " for details.</span>"
                                  ))
                              )
                       ),
                       column(width = 1),
                       column(width = 6,
                              div(style = "height:10px;")
                       )
                     ),
                     # Row 1: by_marker
                     fluidRow(
                       column(width = 5,
                              fileInput(ns("cnv_file_marker"),
                                        label = HTML("HMM Results by Marker <small style='color:grey;font-weight:normal'>(<em>_by_marker.csv</em>)</small>"),
                                        accept = c(".csv", ".gz"), width = "80%")
                       ),
                       column(width = 1),
                       column(width = 6,
                              tags$label("Choose a built-in dataset"),
                              selectInput(
                                ns("cnv_builtin_dataset"),
                                label   = NULL,
                                choices = c("-- Select a dataset --" = "",
                                            "Alfalfa F1 validation population" = "alfalfa_3k_f1"),
                                selected = "alfalfa_3k_f1", width = "80%"
                              )
                       )
                     ),
                     # Row 2: by_window
                     fluidRow(
                       column(width = 5,
                              fileInput(ns("cnv_file_window"),
                                        label = HTML("HMM Results by Window <small style='color:grey;font-weight:normal'>(<em>_by_window.csv</em>)</small>"),
                                        accept = c(".csv", ".gz"), width = "80%")
                       ),
                       column(width = 1),
                       column(width = 6)
                     ),
                     # Row 3: params
                     fluidRow(
                       column(width = 5,
                              fileInput(ns("cnv_file_params"),
                                        label = HTML("HMM Parameters <small style='color:grey;font-weight:normal'>(<em>_params.rds</em>)</small>"),
                                        accept = c(".rds"), width = "80%")
                       ),
                       column(width = 1),
                       column(width = 6)
                     ),
                     # Row 5: Passport file upload
                     fluidRow(
                       column(width = 5,
                              fileInput(ns("passport_file"), "Upload Passport File (CSV)", accept = c(".csv", ".tsv", ".txt", ".gz"), width = "80%")
                       ),
                       column(width = 1),
                       column(width = 6,
                              tags$label("Choose a built-in passport"),
                              selectInput(
                                ns("cnv_builtin_passport"),
                                label   = NULL,
                                choices = c("-- Select a passport --" = "",
                                            "Alfalfa F1 validation population" = "alfalfa_3k_f1"),
                                selected = "alfalfa_3k_f1", width = "80%"
                              )
                       )
                     ),
                     # Row 4: buttons
                     fluidRow(
                       column(width = 5,
                              actionButton(ns("cnv_load_file"), "Load Files", icon = icon("upload"),
                                           class = "btn-info")
                       ),
                       column(width = 1),
                       column(width = 6,
                              actionButton(ns("cnv_load_dataset"), "Load Dataset", icon = icon("database"),
                                           class = "btn-success")
                       )
                     ),
                     # Row 6: Column selector (shown after upload)
                     fluidRow(
                       column(width = 5,
                              uiOutput(ns("passport_sample_col_ui"))
                       ),
                       column(width = 1),
                       column(width = 6)
                     )
                 ), br(),
                 # --- Progress bar ---
                 fluidRow(
                   column(width = 12,
                          progressBar(id = ns("pb_cnv"), value = 0,
                                      title = "", display_pct = FALSE,
                                      status = "info", striped = TRUE)
                   )
                 ), hr(),
                 # --- Dataset info panels ---
                 fluidRow(
                   column(width = 12,
                          conditionalPanel(
                            condition = sprintf("input['%s'] == 'alfalfa_3k'", ns("cnv_builtin_dataset")),
                            div(style = "border-left: 4px solid #6f42c1; background:#f8f9fa; border-radius:4px; padding: 12px 12px 12px 16px; margin-bottom:8px;",
                                HTML(paste0(
                                  "<h5><b>Example Dataset: Alfalfa F1 Population</b></h5>",
                                  "<p>This dataset includes F1 populations of alfalfa, validated using the Alfalfa 3k DArTag marker panel. It demonstrates the application of GenoBrew functionalities to diverse sequencing methods.</p>",
                                  "<ul>",
                                  "  <li><b>Samples:</b> 183 progenies and 2 parents</li>",
                                  "  <li><b>Source:</b> Zhao, D. (2023). \"A public mid-density genotyping platform for alfalfa (Medicago sativa L.)\". Genetic Resources, 4(8), pp. 55–63. <a href='https://doi.org/10.46265/genresj.EMOR6509' target='_blank'>DOI: 10.46265/genresj.EMOR6509</a>.</li>",
                                  "  <li><b>Genotyping Method:</b> DArTag (mid-density genotyping platform)</li>",
                                  "  <li><b>Total Markers:</b> 2,766 </li>",
                                  "  <li><b>Panel Comparison:</b> Markers intersecting with the DArTag 3k Marker Panel</li>",
                                  "</ul>"
                                ))
                            )
                          )
                   )
                 ),
                 fluidRow(
                   column(width = 12,
                          div(style = "display:inline-block; float:right",
                              dropdownButton(
                                HTML("<b>Input files</b>"),
                                p(downloadButton(ns("download_cnv_example"), ""), "CNV Example File"),
                                p(HTML("<b>Parameters description:</b>"), actionButton(ns("goPar"), icon("arrow-up-right-from-square", verify_fa = FALSE))), hr(),
                                p(HTML("<b>Results description:</b>"),     actionButton(ns("goRes"), icon("arrow-up-right-from-square", verify_fa = FALSE))), hr(),
                                p(HTML("<b>How to cite:</b>"),             actionButton(ns("goCite"), icon("arrow-up-right-from-square", verify_fa = FALSE))), hr(),
                                actionButton(ns("cnv_summary"), "Summary"),
                                circle = FALSE,
                                status = "warning",
                                icon = icon("info"), width = "300px",
                                tooltip = tooltipOptions(title = "Click to see info!")
                              )
                          )
                   )
                 )
             )  # end box
      ),
      # --- Select Samples box ---
      column(width = 12,
             box(
               title = "Select Samples", status = "info", solidHeader = TRUE,
               icon = icon("users"), width = 12, collapsible = TRUE, collapsed = FALSE,
               tabsetPanel(
                 id = ns("sample_select_tabs"),
                 type = "tabs",
                 tabPanel(
                   title = tagList(icon("user"), " By Sample"), 
                   value = "by_sample",
                   br(),
                   fluidRow(
                     column(width = 12,
                            pickerInput(
                              ns("cnv_filter_samples"),
                              label   = NULL,
                              choices = NULL,
                              selected = NULL,
                              multiple = TRUE,
                              options  = pickerOptions(
                                actionsBox            = TRUE,
                                liveSearch            = TRUE,
                                liveSearchPlaceholder = "Search samples...",
                                selectedTextFormat    = "count > 3",
                                countSelectedText     = "{0} of {1} samples selected",
                                noneSelectedText      = "No samples selected",
                                selectAllText         = "Select All",
                                deselectAllText       = "Deselect All",
                                size = 12
                              ),
                              width = "100%"
                            ),
                            helpText("All samples are selected by default. Deselect to exclude from plots.")
                     )
                   )
                 ),
                 tabPanel(
                   title = tagList(icon("sitemap"), " By Family"),
                   value = "by_family",
                   br(),
                   fluidRow(
                     column(width = 6,
                            pickerInput(
                              ns("cnv_filter_families"),
                              label   = tags$label("Select families", style = "font-weight:bold"),
                              choices  = NULL,
                              selected = NULL,
                              multiple = FALSE,
                              options  = pickerOptions(
                                actionsBox            = TRUE,
                                liveSearch            = TRUE,
                                liveSearchPlaceholder = "Search families...",
                                selectedTextFormat    = "count > 3",
                                countSelectedText     = "{0} of {1} families selected",
                                noneSelectedText      = "No families selected",
                                selectAllText         = "Select All",
                                deselectAllText       = "Deselect All",
                                size = 12
                              ),
                              width = "100%"
                            ),
                            helpText("Selecting a family will include all samples belonging to it.")
                     ),
                     column(width = 6,
                            tags$label("Samples in selected families", style = "font-weight:bold"),
                            verbatimTextOutput(ns("cnv_family_sample_preview"))
                     )
                   )
                 )
               ), br(),
               # --- CNV profile ---
               box(
                 title = "CNV Profile", status = "info", solidHeader = FALSE,
                 icon = icon("chart-bar"),
                 width = 12, collapsible = TRUE, collapsed = TRUE,
                 fluidRow(
                   column(width = 3,
                          numericInput(ns("gray_CN"), label = "Gray color CN",
                                       value = 2L, min = 1L, max = 12L, step = 1L, width = "50%")
                   ),                   
                   column(width = 3,
                          tags$label("Interactive plot"),
                          prettyRadioButtons(
                            ns("interactive"),
                            label    = NULL,
                            choices  = c("TRUE", "FALSE"),
                            selected = "TRUE",
                            inline   = TRUE,
                            status   = "info"
                          )
                   ),
                   column(width = 3,
                          tags$label("Add heterozygosity"),
                          prettyRadioButtons(
                            ns("add_heterozygosity"),
                            label    = NULL,
                            choices  = c("TRUE", "FALSE"),
                            selected = "TRUE",
                            inline   = TRUE,
                            status   = "info"
                          )
                   )
                 ),
                 column(width = 6,
                        actionButton(ns("cnv_profile_plot"), "Build Plot", icon = icon("chart-bar"),
                                     class = "btn-success")
                 ), br(),
                 fluidRow(
                   column(width = 12,
                          progressBar(id = ns("cnv_plot"), value = 0,
                                      title = "", display_pct = FALSE,
                                      status = "info", striped = TRUE)
                   )
                 ), br(),
                 fluidRow(
                   column(width = 12,
                          uiOutput(ns("cnv_compare_plot_ui"))
                   )
                 ), br(),
                 fluidRow(
                   column(width = 12,
                          div(style = "float:left",
                              dropdownButton(
                                tags$h3("Save CNV Compare Plot"),
                                selectInput(ns("cnv_image_type"), "File Type", choices = c("jpeg","tiff","png","svg", "html"), selected = "html"),
                                sliderInput(ns("cnv_image_res"), "Resolution", value = 300, min = 50, max = 1000, step = 50),
                                sliderInput(ns("cnv_image_width"), "Width", value = 10, min = 1, max = 20, step = 0.5),
                                sliderInput(ns("cnv_image_height"), "Height", value = 6, min = 1, max = 20, step = 0.5),
                                downloadButton(ns("download_cnv_plot"), "Save Image"),
                                circle = FALSE, status = "danger",
                                icon = icon("floppy-disk"), width = "300px", label = "Save",
                                tooltip = tooltipOptions(title = "Save CNV Compare plot")
                              )
                          )
                   )
                 )
               ), br(),
               box(
                 title = "BAF and Z-scores", status = "info", solidHeader = FALSE,
                 icon = icon("chart-bar"),
                 width = 12, collapsible = TRUE, collapsed = FALSE,
                 fluidRow(
                   column(width = 12,
                          progressBar(id = ns("baf_z_plot_bar"), value = 0,
                                      title = "", display_pct = FALSE,
                                      status = "info", striped = TRUE)
                   ), br(),
                   column(width = 12,
                          plotOutput(ns("baf_z_plot"), height = "800px", width = "100%")
                   ), br(),
                   column(width = 12,
                          pickerInput(
                            ns("cnv_filter_samples_baf"),
                            label   = NULL,
                            choices = NULL,
                            selected = NULL,
                            multiple = FALSE,
                            options  = pickerOptions(
                              actionsBox            = TRUE,
                              liveSearch            = TRUE,
                              liveSearchPlaceholder = "Search samples...",
                              selectedTextFormat    = "count > 3",
                              countSelectedText     = "{0} of {1} samples selected",
                              noneSelectedText      = "No samples selected",
                              selectAllText         = "Select All",
                              deselectAllText       = "Deselect All",
                              size = 12
                            ),
                            width = "100%"
                          ),
                          helpText("First sample is selected by default. Choose another or click in the graphic above to update the plot.")
                   ), br(),
                   column(width = 3,
                          tags$label("Remove dots"),
                          prettyRadioButtons(
                            ns("summarize"),
                            label    = NULL,
                            choices  = c("TRUE", "FALSE"),
                            selected = "FALSE",
                            inline   = TRUE,
                            status   = "info"
                          )
                   ),
                   column(width = 3,
                          tags$label("Summarize Z dots by mean"),
                          prettyRadioButtons(
                            ns("summarize_z"),
                            label    = NULL,
                            choices  = c("TRUE", "FALSE"),
                            selected = "TRUE",
                            inline   = TRUE,
                            status   = "info"
                          )
                   ),
                   column(width = 3,
                          tags$label("Show windows lines"),
                          prettyRadioButtons(
                            ns("show_windows_lines"),
                            label    = NULL,
                            choices  = c("TRUE", "FALSE"),
                            selected = "FALSE",
                            inline   = TRUE,
                            status   = "info"
                          )
                   )
                 ), br(),
                 fluidRow(
                   column(width = 12,
                          div(style = "float:left",
                              dropdownButton(
                                tags$h3("Save BAF and Z-scores Plot"),
                                selectInput(ns("baf_image_type"), "File Type", choices = c("jpeg","tiff","png","svg"), selected = "jpeg"),
                                sliderInput(ns("baf_image_res"), "Resolution", value = 300, min = 50, max = 1000, step = 50),
                                sliderInput(ns("baf_image_width"), "Width", value = 10, min = 1, max = 20, step = 0.5),
                                sliderInput(ns("baf_image_height"), "Height", value = 6, min = 1, max = 20, step = 0.5),
                                downloadButton(ns("download_baf_plot"), "Save Image"),
                                circle = FALSE, status = "danger",
                                icon = icon("floppy-disk"), width = "300px", label = "Save",
                                tooltip = tooltipOptions(title = "Save CNV plot")
                              )
                          )
                   )
                 )
               )
             )
      )
    )
  )
}

#' cnv Server Functions
#'
#' @importFrom graphics axis hist points
#' @import ggplot2
#' @importFrom scales comma_format
#' @importFrom grDevices dev.off jpeg png tiff svg
#' @importFrom shinyWidgets updateProgressBar progressBar updatePickerInput
#' @import Qploidy
#' @importFrom tidyr separate_rows
#' @importFrom dplyr mutate filter select
#' @importFrom shinydisconnect disconnectMessage
#' @importFrom plotly renderPlotly plotlyOutput ggplotly event_data
#' @import shiny 
#' @importFrom bs4Dash updatebs4TabItems updateBox
#' @importFrom dplyr %>%
#' @importFrom data.table fread
#'
#' @noRd
mod_cnv_server <- function(input, output, session, parent_session){
  
  ns <- session$ns
  
  
  # Qploidy HMM data storage
  cnv_items <- reactiveValues(
    hmm_CN     = NULL,   
    passport_df = NULL
  )
  
  # --- Reactive storage for dataset sample/family metadata ---
  choices <- reactiveValues(
    samples  = character(0),
    families = character(0),
    sample_family_map = data.frame()   # data.frame with columns: Sample, Family
  )
  
  # Built-in dataset file paths (inst/ directory)
  builtin_cnv_paths <- list(
    alfalfa_3k_f1 = list(
      marker = "https://github.com/Breeding-Insight/BIGapp-PanelHub/raw/refs/heads/long_seq/alfalfa/GenoBrew_example/alfalfa_f1_hmm_CN_estimation_by_marker.csv.gz",
      window = "https://github.com/Breeding-Insight/BIGapp-PanelHub/raw/refs/heads/long_seq/alfalfa/GenoBrew_example/alfalfa_f1_hmm_CN_estimation_by_window.csv.gz",
      params = "https://github.com/Breeding-Insight/BIGapp-PanelHub/raw/refs/heads/long_seq/alfalfa/GenoBrew_example/alfalfa_f1_hmm_CN_estimation_params.rds"
    )
  )
  
  builtin_passport_paths <- list(
    alfalfa_3k_f1 = "https://github.com/Breeding-Insight/BIGapp-PanelHub/raw/refs/heads/long_seq/alfalfa/GenoBrew_example/alfalfa_F1_passport.csv"
  )
  
  # Load built-in dataset using read_hmm_CN
  observeEvent(input$cnv_load_dataset, {
    req(nzchar(input$cnv_builtin_dataset))
    paths <- builtin_cnv_paths[[input$cnv_builtin_dataset]]
    req(!is.null(paths))
    updateProgressBar(session, "pb_cnv", value = 10, title = "Loading Qploidy HMM results...")
    
    marker_path <- paths$marker
    window_path <- paths$window
    params_path <- paths$params

    req(file.exists(marker_path) | grepl("^https?://", marker_path),
        file.exists(window_path) | grepl("^https?://", window_path),
        file.exists(params_path) | grepl("^https?://", params_path))

    cnv_items$hmm_CN <- read_hmm_CN(by_window_file = window_path, 
                                    by_marker_file = marker_path, 
                                    params_file = params_path)

    updateProgressBar(session, "pb_cnv", value = 50, title = "Qploidy HMM results loaded.")
    
  })
  
  observeEvent(input$cnv_load_dataset, {
    req(nzchar(input$cnv_builtin_passport))
    paths <- builtin_passport_paths[[input$cnv_builtin_passport]]
    req(!is.null(paths))
    updateProgressBar(session, "pb_cnv", value = 50, title = "Loading passport data...")
    
    passport_path <- paths
    req(file.exists(passport_path) | grepl("^https?://", passport_path))
    cnv_items$passport_df <- read.csv(passport_path)
    updateProgressBar(session, "pb_cnv", value = 55, title = "Passport data loaded.")
    
  })
  
  # Load uploaded files
  observeEvent(input$cnv_load_file, {
    req(input$cnv_file_marker, input$cnv_file_window)
    updateProgressBar(session, "pb_cnv", value = 10, title = "Loading Qploidy HMM results...")
    
    marker_path <- input$cnv_file_marker$datapath
    window_path <- input$cnv_file_window$datapath
    params_path <- if (!is.null(input$cnv_file_params)) input$cnv_file_params$datapath else NULL

    cnv_items$hmm_CN <- read_hmm_CN(marker_path, window_path, params_path)
    updateProgressBar(session, "pb_cnv", value = 50, title = "Qploidy HMM results loaded.")
  })
  
  observeEvent(input$cnv_load_file, {
    req(nzchar(input$passport_file))
    updateProgressBar(session, "pb_cnv", value = 50, title = "Loading passport data...")
    
    passport_path <- input$passport_file$datapath
    cnv_items$passport_df <- read.csv(passport_path)
    updateProgressBar(session, "pb_cnv", value = 55, title = "Passport data loaded.")
    
  })
  
  observe({
    req(cnv_items$hmm_CN, cnv_items$passport_df)
    
    updateProgressBar(session, "pb_cnv", value = 95, title = "Updating family-sample mapping...")
    
    df <- cnv_items$passport_df
    # Quality check: report any mismatches between passport and VCF sample names
    samples <- unique(cnv_items$hmm_CN$by_window$Sample)
    if(length(which(!df$ID %in% samples)) > 0) df <- df[-which(!df$ID %in% samples),]
    
    # Reshape passport to long format so multi-family individuals are expanded
    df_long <- df %>%
      mutate(fam = as.character(fam)) %>%
      separate_rows(fam, sep = ",") %>%
      mutate(fam = as.integer(fam))
    
    # Build per-family sample lists and generation labels
    fam_list <- split(df_long$ID,          df_long$fam)
    rela      <- split(df_long$generation, df_long$fam)
    
    idx <- lapply(rela, function(x) which(x == "Parent"))
    
    parents <- vector()
    for(i in 1:length(fam_list)) parents[i] <- paste0(fam_list[[i]][idx[[i]]], collapse = " x ")
    
    fam_select <- as.list(1:length(fam_list))
    names(fam_select) <- parents
    choices$families <- fam_select
    choices$sample_family_map <- fam_list
    choices$relations <- rela
    # Update sample picker choices
    updatePickerInput(session, "cnv_filter_families",
                      choices = fam_select,
                      selected = fam_select)
  })
  
  # Preview samples belonging to selected families
  output$cnv_family_sample_preview <- renderText({
    req(length(input$cnv_filter_families) > 0)
    if (length(choices$sample_family_map) == 0) {
      return("Family-sample mapping not yet available for this dataset.")
    }
    sel <- choices$sample_family_map[[input$cnv_filter_families]]
    relat <- choices$relations[[input$cnv_filter_families]]
    if (length(sel) == 0) return("No samples found for selected families.")
    paste(paste0(relat, "-",sel), collapse = "\n")
  })
  
  observe({
    req(cnv_items$hmm_CN)
    updateProgressBar(session, "pb_cnv", value = 100, title = "Updating sample picker choices...")
    
    samples <- unique(cnv_items$hmm_CN$by_window$Sample)
    
    # Update sample picker choices
    updatePickerInput(session, "cnv_filter_samples",
                      choices = samples,
                      selected = samples)
    
    updatePickerInput(session, "cnv_filter_samples_baf",
                      choices = samples,
                      selected = NULL)
  })
  
  dosages <- reactive({
    req(cnv_items$hmm_CN, input$add_heterozygosity)
    if(input$add_heterozygosity == "TRUE") {
      updateProgressBar(session, "cnv_plot", value = 50, title = "Calling dosages for heterozygosity estimation...")
      
      call_hmm_dosages(cnv_items$hmm_CN, bw = 0.15, dist = "gaussian", add_uniform = FALSE, uniform_weight = 0.01)
    } else NULL
  })
  
  cnv_profile <- eventReactive(input$cnv_profile_plot, {
    req(cnv_items$hmm_CN)
    updateProgressBar(session, "cnv_plot", value = 0, title = "Building CNV profile plot...")
    
    
    # Determine which tab is active for sample selection
    samples_to_plot <- NULL
    if (!is.null(input$sample_select_tabs) && input$sample_select_tabs == "by_family") {
      # Defensive: handle NULL or empty selection
      fam <- input$cnv_filter_families
      if (!is.null(fam) && length(fam) > 0 && !is.null(choices$sample_family_map[[fam]])) {
        samples_to_plot <- choices$sample_family_map[[fam]]
      } else {
        samples_to_plot <- character(0)
      }
    } else {
      samples_to_plot <- input$cnv_filter_samples
    }
    
    plot <- compare_cn_track(cnv_items$hmm_CN, 
                             samples_to_plot = samples_to_plot, 
                             facet_nrow = 1,
                             gray_CN = input$gray_CN, 
                             add_het = input$add_heterozygosity == "TRUE",
                             hmm_dosage_calls = dosages(),
                             interactive = TRUE)
    
    updateProgressBar(session, "cnv_plot", value = 100, title = "CNV profile plot ready.")
    
    plot
  })
  
  ##########
  
  output$cnv_compare_plotly <- renderPlotly({
    req(cnv_profile())
    ggplotly(cnv_profile(), source = "cnv_source")
  })
  
  output$cnv_compare_plot_ui <- renderUI({
    plotlyOutput(ns("cnv_compare_plotly"), height = "600px")
  })
  
  # Simple ggplot click handler - manual coordinate detection
  observeEvent(input$cnv_plot_click, {
    if (!is.null(input$cnv_plot_click)) {
      tryCatch({
        data <- cnv_profile()@data
        click_y <- input$cnv_plot_click$y
        
        # Get unique samples and their order (bottom to top)
        samples <- unique(data$Sample)
        sample_levels <- rev(samples)  # reversed because ggplot plots bottom to top
        
        # Find which sample was clicked based on y coordinate
        sample_index <- round(click_y)
        
        if (sample_index >= 1 && sample_index <= length(sample_levels)) {
          clicked_sample <- sample_levels[sample_index]
          updatePickerInput(session, "cnv_filter_samples_baf", selected = as.character(clicked_sample))
        }
      }, error = function(e) {
        # Silently handle errors
      })
    }
  })
  
  # Plotly click handler - try different event source
  observeEvent(event_data("plotly_click"), {
    click_data <- event_data("plotly_click")
    
    if(!is.null(click_data)) {
      tryCatch({
        # Extract y value which should be the sample name
        if ("y" %in% names(click_data)) {
          clicked_sample <- click_data$y
          updatePickerInput(session, "cnv_filter_samples_baf", selected = as.character(clicked_sample))
        }
      }, error = function(e) {
        # Silently handle errors
      })
    }
  })
  
  ######
  
  baf_z <- reactive({
    req(cnv_items$hmm_CN, cnv_profile(), input$cnv_filter_samples_baf, !is.null(input$cnv_filter_samples_baf))
    updateProgressBar(session, "baf_z_plot_bar", value = 10, title = "CNV profile plot ready.")
    
    plot <- plot_cn_track(cnv_items$hmm_CN, 
                          sample_id = input$cnv_filter_samples_baf,
                          summarized = input$summarize == "TRUE",
                          z_by_mean = input$summarize_z == "TRUE",
                          show_window_lines = input$show_windows_lines == "TRUE")
    
    updateProgressBar(session, "baf_z_plot_bar", value = 100, title = "CNV profile plot ready.")
    
    plot
  })
  
  output$baf_z_plot <- renderPlot({
    req(baf_z())
    baf_z()
  })
  
  # Help links
  observeEvent(input$goPar, {
    # change to help tab
    updatebs4TabItems(session = parent_session, inputId = "MainMenu",
                      selected = "help")
    
    # select specific tab
    updateTabsetPanel(session = parent_session, inputId = "Genomic_cnv_tabset",
                      selected = "Genomic_cnv_par")
    # expand specific box
    updateBox(id = "Genomic_cnv_box", action = "toggle", session = parent_session)
  })
  
  observeEvent(input$goRes, {
    # change to help tab
    updatebs4TabItems(session = parent_session, inputId = "MainMenu",
                      selected = "help")
    
    # select specific tab
    updateTabsetPanel(session = parent_session, inputId = "Genomic_cnv_tabset",
                      selected = "Genomic_cnv_results")
    # expand specific box
    updateBox(id = "Genomic_cnv_box", action = "toggle", session = parent_session)
  })
  
  observeEvent(input$goCite, {
    # change to help tab
    updatebs4TabItems(session = parent_session, inputId = "MainMenu",
                      selected = "help")
    
    # select specific tab
    updateTabsetPanel(session = parent_session, inputId = "Genomic_cnv_tabset",
                      selected = "Genomic_cnv_cite")
    # expand specific box
    updateBox(id = "Genomic_cnv_box", action = "toggle", session = parent_session)
  })
  
  output$download_cnv_example <- downloadHandler(
    filename = function() {
      paste0("BIGapp_VCF_Example_file.vcf.gz")
    },
    content = function(file) {
      ex <- system.file("iris_DArT_VCF.vcf.gz", package = "BIGapp")
      file.copy(ex, file)
    })
  
  # Download handler for CNV plot
  output$download_cnv_plot <- downloadHandler(
    filename = function() {
      paste("CNV_Plot", Sys.Date(), ".", input$cnv_image_type, sep = "")
    },
    content = function(file) {
      req(cnv_profile())
      if(input$cnv_image_type == "html") {
        htmlwidgets::saveWidget(cnv_profile(), file)
      } else {
        
        plot <- compare_cn_track(cnv_items$hmm_CN, 
                                 samples_to_plot = samples_to_plot, 
                                 facet_nrow = 1,
                                 gray_CN = input$gray_CN, 
                                 add_het = input$add_heterozygosity == "TRUE",
                                 hmm_dosage_calls = dosages(),
                                 interactive = FALSE)
        ggsave(
          filename = file,
          plot = plot,
          device = input$cnv_image_type,
          dpi = input$cnv_image_res,
          width = input$cnv_image_width,
          height = input$cnv_image_height
        )
      }
    }
  )
  
  # Download handler for BAF and Z-scores plot
  output$download_baf_plot <- downloadHandler(
    filename = function() {
      paste("BAF_Zscores_Plot", Sys.Date(), ".", input$baf_image_type, sep = "")
    },
    content = function(file) {
      req(baf_z())
      ggsave(
        filename = file,
        plot = baf_z(),
        device = input$baf_image_type,
        dpi = input$baf_image_res,
        width = input$baf_image_width,
        height = input$baf_image_height
      )
    }
  )
  
  ##Summary Info
  cnv_summary_info <- function() {
    # Handle possible NULL values for inputs
    dosage_file_name <- if (!is.null(input$cnv_file$name)) input$cnv_file$name else "No file selected"
    selected_ploidy <- if (!is.null(input$cnv_ploidy)) as.character(input$cnv_ploidy) else "Not selected"
    
    # Print the summary information
    cat(
      "BIGapp Summary Metrics Summary\n",
      "\n",
      paste0("Date: ", Sys.Date()), "\n",
      paste(R.Version()$version.string), "\n",
      "\n",
      "### Input Files ###\n",
      "\n",
      paste("Input Genotype File:", dosage_file_name), "\n",
      "\n",
      "### User Selected Parameters ###\n",
      "\n",
      paste("Selected Ploidy:", selected_ploidy), "\n",
      "\n",
      "### R Packages Used ###\n",
      "\n",
      paste("GenoBrew:", packageVersion("GenoBrew")), "\n",
      paste("Qploidy:", packageVersion("Qploidy")), "\n",
      paste("ggplot2:", packageVersion("ggplot2")), "\n",
      paste("vcfR:", packageVersion("vcfR")), "\n",
      sep = ""
    )
  }
  
  # Popup for analysis summary
  observeEvent(input$cnv_summary, {
    showModal(modalDialog(
      title = "Summary Information",
      size = "l",
      easyClose = TRUE,
      footer = tagList(
        modalButton("Close"),
        downloadButton("download_cnv_info", "Download")
      ),
      pre(
        paste(capture.output(cnv_summary_info()), collapse = "\n")
      )
    ))
  })
  
  
  # Download Summary Info
  output$download_cnv_info <- downloadHandler(
    filename = function() {
      paste("cnv_summary_", Sys.Date(), ".txt", sep = "")
    },
    content = function(file) {
      # Write the summary info to a file
      writeLines(paste(capture.output(cnv_summary_info()), collapse = "\n"), file)
    }
  )
}

## To be copied in the UI
# mod_cnv_ui("cnv_1")

## To be copied in the server
# mod_cnv_server("cnv_1")
